#!/usr/bin/env bash
CC=gcc
SRC= main.c holberton.c
OBJ= $(SRC:.c=.o)
NAME=holberton
RM= rm -f
all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)
.PHONY: clean oclean fclean re
clean:
	$(RM) *~ holberton
oclean:
	$(RM) main.o holberton.o
fclean: clean oclean
re: oclean all
