#!/usr/bin/env bash
CC=gcc
SRC= main.c holberton.c
OBJ= $(SRC:.c=.o)
NAME=holberton
CFLAGS=-Wall -Werror -Wextra -pedantic
RM= rm -f
all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)
clean:
	$(RM) *~ holberton
oclean:
	$(RM) main.o holberton.o
fclean:
	$(RM) *~ holberton
	$(RM) main.o holberton.o
re: oclean all
